### ISSUE TITLE
Unable to load NPm module

### ISSUE THREAD

**Issue by amikri19** [mrded/textAngular-uploadImage#4]
npm install --save textAngular-uploadImage
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/textAngular-uploadImage - Not found
npm ERR! 404
npm ERR! 404  'textAngular-uploadImage@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404

**Comment by mrded** [comment]
Try lower case

**Comment by mrded** [comment]
The readme has been updated
